# Site settings
title: Port 80
email: scott@deepfishlab.com
description: > # this means to ignore newlines until "baseurl:"
  S.E. Todd's Personal and software development blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://port-80.org" # the base hostname & protocol for your site
twitter_username: setodd
github_username:  stodd

# Build settings
markdown: kramdown
